/**
 * @author Anthony Altieri on 11/12/16.
 */

// Questions
const QUESTION_ASKED = 'QUESTION_ASKED';
const QUESTION_REMOVED = 'QUESTION_REMOVED';
const VOTE_ADD = 'VOTE_ADD';
const VOTE_REMOVE = 'VOTE_REMOVE';
const RESPONSE_ADD = 'ADD_RESPONSE';
const RESPONSE_REMOVED = 'RESPONSE_REMOVED';
const ADD_FLAG = 'ADD_FLAG';
const REMOVE_FLAG = 'REMOVE_FLAG';



export default {
  QUESTION_ASKED,
  QUESTION_REMOVED,
  VOTE_ADD,
  VOTE_REMOVE,
  RESPONSE_ADD,
  RESPONSE_REMOVED,
  ADD_FLAG,
  REMOVE_FLAG,
}
