/**
 * @author Anthony Altieri on 11/12/16.
 */

// Questions
const QUESTION_ASKED = 'QUESTION_ASKED';
const QUESTION_REMOVED = 'QUESTION_REMOVED';
const VOTE_ADD = 'VOTE_ADD';
const VOTE_REMOVE = 'VOTE_REMOVE';
const RESPONSE_ADD = 'RESPONSE_ADD';
const RESPONSE_REMOVED = 'RESPONSE_REMOVED';
const ADD_FLAG = 'FLAG_ADD';
const REMOVE_FLAG = 'FLAG_REMOVE';
const ASSESSMENT_ACTIVATED = 'ASSESSMENT_ACTIVATED';
const ASSESSMENT_DEACTIVATED = 'ASSESSMENT_DEACTIVATED';
const INSTANT_ASSESSMENT_ANSWERED = 'INSTANT_ASSESSMENT_ANSWERED';
const REFLECTIVE_ASSESSMENT_REVIEWED = 'REFLECTIVE_ASSESSMENT_REVIEWED';
const REFLECTIVE_ASSESSMENT_ANSWERED = 'REFLECTIVE_ASSESSMENT_ANSWERED';
const REFLECTIVE_ASSESSMENT_START_REVIEW = 'REFLECTIVE_ASSESSMENT_START_REVIEW'
const STUDENT_JOINED_ATTENDANCE = 'STUDENT_JOINED_ATTENDANCE';

export default {
  QUESTION_ASKED,
  QUESTION_REMOVED,
  VOTE_ADD,
  VOTE_REMOVE,
  RESPONSE_ADD,
  RESPONSE_REMOVED,
  ADD_FLAG,
  REMOVE_FLAG,
  ASSESSMENT_ACTIVATED,
  ASSESSMENT_DEACTIVATED,
  INSTANT_ASSESSMENT_ANSWERED,
  REFLECTIVE_ASSESSMENT_REVIEWED,
  REFLECTIVE_ASSESSMENT_ANSWERED,
  REFLECTIVE_ASSESSMENT_START_REVIEW,
  STUDENT_JOINED_ATTENDANCE
}
